# Uncomment this line to define a global platform for your project
platform :ios, '13.0'

# CocoaPods analytics sends network requests to Google Analytics.
# To disable this, uncomment the following line.
# ENV['COCOAPODS_DISABLE_STATS'] = 'true'

# Uncomment this line if you're using Swift or would like to use dynamic frameworks
use_frameworks!

# Prevents Cocoapods from embedding a duplicate Pods framework in the Podfile
install! 'cocoapods', :deterministic_uuids => false

def parse_KV_file(file, separator = '=')
  file_abs_path = File.expand_path(file)
  if !File.exists? file_abs_path
    return [];
  end
  generated_key_values = {}
  skip_line_start_symbols = ["#", "/"]
  File.foreach(file_abs_path) do |line|
    next if skip_line_start_symbols.any? { |symbol| line =~ /^\s*#{symbol}/ }
    plugin = line.split(pattern=separator)
    if plugin.length == 2
      podname = plugin[0].strip()
      path = plugin[1].strip()
      if path.length > 0
        generated_key_values[podname] = path
      else
        puts "Invalid plugin specification: `#{line}`"
      end
    else
      puts "Invalid plugin specification: `#{line}`"
    end
  end
  generated_key_values
end

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end
