# Uncomment this line to define a global platform for your project
platform :ios, '13.0'

# CocoaPods analytics sends network requests to Google Analytics.
# To see the data sent to Google, open:
#   /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/installer/analytics.rb
# To disable this, uncomment:
# ENV['COCOAPODS_DISABLE_STATS'] = 'true'

prepare_command do
  # Workaround for Flutter 3.x compatibility
  system('rm -rf Pods/.symlinks')
  system('rm -rf Pods/Manifest.lock')
end

def parse_KV_file(file, separator='=')
  file_abs_path = File.expand_path(file)
  if !File.exists? file_abs_path
    return [];
  end
  generated_key_values = {}
  skip_line_start_symbols = ["#", "/"]
  File.foreach(file_abs_path) do |line|
    next if skip_line_start_symbols.any? { |symbol| line.start_with?(symbol) }
    separator_index = line.index(separator)
    if separator_index.nil?
      next
    end
    key = line[0..separator_index-1].strip
    value = line[separator_index+1..-1].strip
    generated_key_values[key] = value
  end
  generated_key_values
end

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end
